                                                                                                                                                                                                                                                                                                                                                                                                             
#                                                                                                                                                                                                                                                                                                                                                                                                               
#          CCCCCCCCCCCCC                                            tttt                                                        MMMMMMMM               MMMMMMMM                                                                                                                                tttt               PPPPPPPPPPPPPPPPP                           tttt         hhhhhhh                              
#       CCC::::::::::::C                                         ttt:::t                                                        M:::::::M             M:::::::M                                                                                                                             ttt:::t               P::::::::::::::::P                       ttt:::t         h:::::h                              
#     CC:::::::::::::::C                                         t:::::t                                                        M::::::::M           M::::::::M                                                                                                                             t:::::t               P::::::PPPPPP:::::P                      t:::::t         h:::::h                              
#    C:::::CCCCCCCC::::C                                         t:::::t                                                        M:::::::::M         M:::::::::M                                                                                                                             t:::::t               PP:::::P     P:::::P                     t:::::t         h:::::h                              
#   C:::::C       CCCCCCuuuuuu    uuuuuu      ssssssssss   ttttttt:::::ttttttt       ooooooooooo      mmmmmmm    mmmmmmm        M::::::::::M       M::::::::::M   ooooooooooo vvvvvvv           vvvvvvv eeeeeeeeeeee       mmmmmmm    mmmmmmm       eeeeeeeeeeee    nnnn  nnnnnnnn    ttttttt:::::ttttttt           P::::P     P:::::Paaaaaaaaaaaaa  ttttttt:::::ttttttt    h::::h hhhhh           ssssssssss   
#  C:::::C              u::::u    u::::u    ss::::::::::s  t:::::::::::::::::t     oo:::::::::::oo  mm:::::::m  m:::::::mm      M:::::::::::M     M:::::::::::M oo:::::::::::oov:::::v         v:::::vee::::::::::::ee   mm:::::::m  m:::::::mm   ee::::::::::::ee  n:::nn::::::::nn  t:::::::::::::::::t           P::::P     P:::::Pa::::::::::::a t:::::::::::::::::t    h::::hh:::::hhh      ss::::::::::s  
#  C:::::C              u::::u    u::::u  ss:::::::::::::s t:::::::::::::::::t    o:::::::::::::::om::::::::::mm::::::::::m     M:::::::M::::M   M::::M:::::::Mo:::::::::::::::ov:::::v       v:::::ve::::::eeeee:::::eem::::::::::mm::::::::::m e::::::eeeee:::::een::::::::::::::nn t:::::::::::::::::t           P::::PPPPPP:::::P aaaaaaaaa:::::at:::::::::::::::::t    h::::::::::::::hh  ss:::::::::::::s 
#  C:::::C              u::::u    u::::u  s::::::ssss:::::stttttt:::::::tttttt    o:::::ooooo:::::om::::::::::::::::::::::m     M::::::M M::::M M::::M M::::::Mo:::::ooooo:::::o v:::::v     v:::::ve::::::e     e:::::em::::::::::::::::::::::me::::::e     e:::::enn:::::::::::::::ntttttt:::::::tttttt           P:::::::::::::PP           a::::atttttt:::::::tttttt    h:::::::hhh::::::h s::::::ssss:::::s
#  C:::::C              u::::u    u::::u   s:::::s  ssssss       t:::::t          o::::o     o::::om:::::mmm::::::mmm:::::m     M::::::M  M::::M::::M  M::::::Mo::::o     o::::o  v:::::v   v:::::v e:::::::eeeee::::::em:::::mmm::::::mmm:::::me:::::::eeeee::::::e  n:::::nnnn:::::n      t:::::t                 P::::PPPPPPPPP      aaaaaaa:::::a      t:::::t          h::::::h   h::::::h s:::::s  ssssss 
#  C:::::C              u::::u    u::::u     s::::::s            t:::::t          o::::o     o::::om::::m   m::::m   m::::m     M::::::M   M:::::::M   M::::::Mo::::o     o::::o   v:::::v v:::::v  e:::::::::::::::::e m::::m   m::::m   m::::me:::::::::::::::::e   n::::n    n::::n      t:::::t                 P::::P            aa::::::::::::a      t:::::t          h:::::h     h:::::h   s::::::s      
#  C:::::C              u::::u    u::::u        s::::::s         t:::::t          o::::o     o::::om::::m   m::::m   m::::m     M::::::M    M:::::M    M::::::Mo::::o     o::::o    v:::::v:::::v   e::::::eeeeeeeeeee  m::::m   m::::m   m::::me::::::eeeeeeeeeee    n::::n    n::::n      t:::::t                 P::::P           a::::aaaa::::::a      t:::::t          h:::::h     h:::::h      s::::::s   
#   C:::::C       CCCCCCu:::::uuuu:::::u  ssssss   s:::::s       t:::::t    tttttto::::o     o::::om::::m   m::::m   m::::m     M::::::M     MMMMM     M::::::Mo::::o     o::::o     v:::::::::v    e:::::::e           m::::m   m::::m   m::::me:::::::e             n::::n    n::::n      t:::::t    tttttt       P::::P          a::::a    a:::::a      t:::::t    tttttth:::::h     h:::::hssssss   s:::::s 
#    C:::::CCCCCCCC::::Cu:::::::::::::::uus:::::ssss::::::s      t::::::tttt:::::to:::::ooooo:::::om::::m   m::::m   m::::m     M::::::M               M::::::Mo:::::ooooo:::::o      v:::::::v     e::::::::e          m::::m   m::::m   m::::me::::::::e            n::::n    n::::n      t::::::tttt:::::t     PP::::::PP        a::::a    a:::::a      t::::::tttt:::::th:::::h     h:::::hs:::::ssss::::::s
#     CC:::::::::::::::C u:::::::::::::::us::::::::::::::s       tt::::::::::::::to:::::::::::::::om::::m   m::::m   m::::m     M::::::M               M::::::Mo:::::::::::::::o       v:::::v       e::::::::eeeeeeee  m::::m   m::::m   m::::m e::::::::eeeeeeee    n::::n    n::::n      tt::::::::::::::t     P::::::::P        a:::::aaaa::::::a      tt::::::::::::::th:::::h     h:::::hs::::::::::::::s 
#       CCC::::::::::::C  uu::::::::uu:::u s:::::::::::ss          tt:::::::::::tt oo:::::::::::oo m::::m   m::::m   m::::m     M::::::M               M::::::M oo:::::::::::oo         v:::v         ee:::::::::::::e  m::::m   m::::m   m::::m  ee:::::::::::::e    n::::n    n::::n        tt:::::::::::tt     P::::::::P         a::::::::::aa:::a       tt:::::::::::tth:::::h     h:::::h s:::::::::::ss  
#          CCCCCCCCCCCCC    uuuuuuuu  uuuu  sssssssssss              ttttttttttt     ooooooooooo   mmmmmm   mmmmmm   mmmmmm     MMMMMMMM               MMMMMMMM   ooooooooooo            vvv            eeeeeeeeeeeeee  mmmmmm   mmmmmm   mmmmmm    eeeeeeeeeeeeee    nnnnnn    nnnnnn          ttttttttttt       PPPPPPPPPP          aaaaaaaaaa  aaaa         ttttttttttt  hhhhhhh     hhhhhhh  sssssssssss    
#                                                                                                                                                                                                                                                                                                                                                                                                               
#                                                                                                                                                                                                                                                                                                                                                                                                               
#                                                                                                                                                                                                                                                                                                                                                                                                               
#                                                                                                                                                                                                                                                                                                                                                                                                               
#                                                                                                                                                                                                                                                                                                                                                                                                               
#                                                                                                                                                                                                                                                                                                                                                                                                               
# 
                                                                                                                                                                                   
from direct.showbase.ShowBase import ShowBase
from panda3d.core import *
from direct.actor.Actor import Actor
from direct.directutil import Mopath
from direct.interval.MopathInterval import *

showapp=ShowBase()
actormodel=Actor("EggMod/PathMove.egg",{"PathMoving1":"EggMod/PathMove-Moving.egg"})
modelfollow=actormodel.exposeJoint(None,"modelRoot","Bone")
boxExample=loader.loadModel("box.egg")
boxExample.reparentTo(modelfollow)
actormodel.reparentTo(render)
actormodel.play("PathMoving1")
showapp.run()    
